### PR TITLE
Support parameters for cmd:run

### PR DESCRIPTION
**Pull request by n0n0x**
Did this because I want the DNS port to be published on 127.0.0.1. Could have hardcoded this. But found it challenging and useful to do this extensible just in case anyone wants to add more options.

Cheers!

### CODE REVIEW

**Comment by n0n0x** [comment]
Fixes Issue #27 by using -j <ip>,<ip>,<ip>

**Comment by rossbachp** [comment]
Like this PR:)

**Comment by will-ob** [comment]
+1 :)

**Comment by Kosta-Github** [comment]
+1

**Pull request closed without merging**
